# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2  # Required

# Set the OS and tools
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"  # or 3.12 if you want

# Important: Enable submodules
submodules:
  include: all

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py

# Python dependencies
python:
  install:
    - requirements: docs/source/requirements.txt
